server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filters_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: swagger-ui-custom.html

logging:
  level:
    liquibase: DEBUG

