version: '3.8'
services:
  filters-db:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: filters_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-filters-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  filters-db-test:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: filters_db_test
    environment:
      - POSTGRES_DB=${POSTGRES_DB_TEST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres-filters-data:
